version: '3'
services:
  backend:
    image: yanak38/sendrevenue:latest
    build: .
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx:1.21.3-alpine
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/  
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value: